version: '3'

services:
  postgres:
    container_name: ita-postgres
    image: library/postgres:13.1
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres